// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations/introspection always go through the direct (non-pooled)
    // connection — required when DATABASE_URL is a PgBouncer/transaction
    // pooler string (e.g. Supabase's pooler), which can't run DDL reliably.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
